export const en = {

    // HOME NAVIGATION
    home: "Home",
    habits: "Habits Setup",
    streaks: "Streaks",

    madeBy: "Made by",

    // AUTH
    login: "Login",
    register: "Create Account",
    recoverAccount: "Recover Account",
    password: "Password",
    repeatPassword: "Repeat your password",
    passwordForgotten: "Did you forgot your password? Recover account",
    createAccount: "Don´t you have an account? Create one here",
    loginInstead: "Do you already hace an account? Login here",
    invalidEmail: "Invalid Email",
    passwordRequired: "Password is required",
    passwordCfmRequired: "Password confirmation is required",
    passwordsMatch: "Passwords doesn´t match",
    passwordMin: "Password Min length: 6 characters",
    emailRequired: "Email is required",
    uploadPicture: "Upload Picture",
    cameraOrMedia: "Open camera or select from media library?",
    openCamera: "Open Camera",
    openMedia: "Open Media Library",
    yourName: "Your Name",
    nameRequired: "Name is required",

    // HOME
    hello: "Hello, ",
    emailValidationAlert: "You haven´t validate your email, please check your inbox or:",
    emailValidationButton: "Re-send validation email",
    noHabits: "There´s no habits for today!",
    createOrEdit: "Create or edit one",
    todaysHabits: "Today´s Habits - ",
    left: " left",
    completedAll: "You have completed all your daily habits! Congratulations",
    completedHabits: "Completed Habits: ",
    youHavent: "You haven´t completed any habit today :(",

    // STREAKS
    more: "More",
    theresNoHabits: "There´s no habits! Create one",
    noStreaks: "You don´t have streaks yet, start completing habits!",
    yourStreaks: "Your Streaks",
    youCompleted: "You have completed: ",
    day: "day",
    days: "days",
    inARow: " in a row",
    inARowPlural: " in a row",
    totals: "Totals",

    // CALENDAR
    calendar: "Calendar",
    zeroCompleted: "0 Habits completed",
    lessHalfCompleted: "Less than 50% of daily habits",
    atLeast50: "At least 50% of daily habits completed", 
    atLeast80: "At least 80% of daily habits completed", 
    selectADay: "Select a day with habits history",
    completed: "Completed:",
    incompleted: "Incompleted:",

    // HABITS
    habitsSetup: "Habits Setup",
    addNewHabit: "Add new habit",
    yourHabits: "Your Habits",
    uSure: "Are you sure?",
    habitWillDeleted: "The habit will be deleted permanently",
    cancel: "Cancel",
    delete: "Delete",
    monday: "Monday", 
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",

    // ADD OR EDIT HABIT
    habitNameRequired: "Habit name is required",
    editHabit: "Edit Habit",
    addHabit: "Add Habit",
    chooseIcon: "Choose icon",
    habitName: "Habit Name",
    description: "Description",
    whatDays: "What days do you want to do it?",
    saveHabit: "Save Habit",
    createHabit: "Create Habit",

    //Account
    logout: "Logout",
    doYouLogout: "Do you want to logout?",
    account: "Account",
    uploadPictureAlert: "* Upload a profile picture",
    editProfile: "Edit Profile",
    changePassword: "Change Password",

    // CHANGE PASSWORD
    passwordWillChange: "Your password will change",
    currentPassword: "Your current password",
    newPassword: "New password",
    currentPasswordRequired: "Your current password id required",
    newPasswordRequired: "New password is required",

    // EDIT PROFILE
    profileWillUpdated: "Your profile will be updated",
    confirm: "Confirm",
    forYourSecurity: "For your security, type your password",
    saveChanges: "Save changes",

    // ALERTS - LOADING: AUTH
    creatingAccount: "Creating account...",
    verificationSent: "Verification email sent, check your inbox",
    loggingIn: "Logging in...",
    loggingOut: "Logging out...",
    sendingRecover: "Sending recover email...",
    emailSent: "Email sent, check your inbox",
    sendingValidation: "Sending validation email...",
    updatingAccount: "Updating account info...",
    updatingEmail: "Updating Email...",
    updatingPassword: "Updating Password...",

    // ALERTS - LOADING: HABITS
    creatingHabit: "Creating habit...",
    deletingHabit: "Deleting habit...",
    editingHabit: "Editing habit...",
    completingHabit: "Completing habit...",

    // ERRORS
    'auth/claims-too-large': 'The payload of the delivered claim exceeds the maximum size of 1,000 bytes.',
    'auth/email-already-exists': 'Another user is already using the provided email. Each user must have a unique email.',
    'auth/id-token-expired': 'The Firebase ID token provided has expired.',
    'auth/id-token-revoked': 'The Firebase ID token has been revoked.',
    'auth/insufficient-permission': 'The credential used to initialize the Admin SDK does not have sufficient permission to access the requested Authentication resource. See how to set up a Firebase project if you need to view documentation for generating a credential with appropriate permissions and using it to authenticate Admin SDKs.',
    'auth/internal-error': 'The Authentication server encountered an unexpected error when trying to process the request. For additional information, review the authentication server response, which should be included in the error message. If the error persists, let us know through our error reporting support channel.',
    'auth/invalid-argument': 'An invalid argument was provided for an authentication method. The error message should include additional information.',
    'auth/invalid-claims': 'The delivered custom claims attributes are invalid.',
    'auth/invalid-continue-uri': 'The continue URL must be a valid URL string.',
    'auth/invalid-creation-time': 'The creation time must be a valid UTC date string.',
    'auth/invalid-credential': 'The credential used to authenticate the Admin SDKs cannot be used to perform the desired action.',
    'auth/invalid-disabled-field': 'The value provided for the user disabled property is invalid. It must be a boolean.',
    'auth/invalid-display-name': 'The value provided for the user displayName property is invalid. It must be a non-empty string.',
    'auth/invalid-dynamic-link-domain': 'The provided dynamic link domain is not configured or authorized for the current project.',
    'auth/invalid-email': 'The value provided for the user email property is invalid. It must be a string email address.',
    'auth/invalid-email-verified': 'The value provided for the user emailVerified property is invalid. It must be a boolean.',
    'auth/invalid-hash-algorithm': 'The hash algorithm must match the strings in the list of compatible algorithms.',
    'auth/invalid-hash-block-size': 'The hash block size must be a valid number.',
    'auth/invalid-hash-derived-key-length': 'The length of the derived key from the hash must be a valid number.',
    'auth/invalid-hash-key': 'The hash key must be a valid byte buffer.',
    'auth/invalid-hash-memory-cost': 'The hash memory cost must be a valid number.',
    'auth/invalid-hash-parallelization': 'The hash parallelization must be a valid number.',
    'auth/invalid-hash-rounds': 'The hash rounds must be a valid number.',
    'auth/invalid-hash-salt-separator': 'The salt separator field of the hash algorithm must be a valid byte buffer.',
    'auth/invalid-id-token': 'The ID token provided is not a valid Firebase ID token.',
    'auth/invalid-last-sign-in-time': 'The last sign-in time must be a valid UTC format date string.',
    'auth/invalid-page-token': 'The next page token provided in listUsers() is invalid. It must be a non-empty valid string.',
    'auth/invalid-password': 'The value provided for the user password property is invalid. It must be a string with at least six characters.',
    'auth/invalid-password-hash': 'Password hash must be a valid byte buffer.',
    'auth/invalid-password-salt': 'Password salt must be a valid byte buffer.',
    'auth/invalid-phone-number': 'The value provided for phoneNumber is invalid. It must be a non-empty identifier string that complies with the E.164 standard.',
    'auth/invalid-photo-url': 'The value provided for the user photoURL property is invalid. It must be a valid string URL.',
    'auth/invalid-provider-data': 'providerData must be an array of UserInfo objects.',
    'auth/invalid-provider-id': 'providerId must be a valid compatible provider identifier string.',
    'auth/invalid-oauth-responsetype': 'Only one OAuth responseType should be configured as true.',
    'auth/invalid-session-cookie-duration': 'Session cookie duration must be a valid number in milliseconds ranging from 5 minutes to 2 weeks.',
    'auth/invalid-uid': 'The provided uid must be a non-empty string with a maximum of 128 characters.',
    'auth/invalid-user-import': 'The user record to import is not valid.',
    'auth/maximum-user-count-exceeded': 'The maximum allowed user count to import has been exceeded.',
    'auth/missing-android-pkg-name': 'If installing the app for Android is mandatory, an Android package name must be provided.',
    'auth/missing-continue-uri': 'A valid continue URL must be provided in the request.',
    'auth/missing-hash-algorithm': 'To import users with password hashes, the hash algorithm and its parameters must be provided.',
    'auth/missing-ios-bundle-id': 'An iOS bundle ID is missing from the request.',
    'auth/missing-uid': 'A uid identifier is required for the current operation.',
    'auth/missing-oauth-client-secret': 'The client secret in the OAuth configuration is required to enable the OIDC code flow.',
    'auth/operation-not-allowed': 'The provided access provider is disabled for your Firebase project. Enable it in the Firebase console Access Method section.',
    'auth/phone-number-already-exists': 'Another user is already using the provided phoneNumber. Each user must have a unique phoneNumber.',
    'auth/project-not-found': 'No Firebase project was found for the credential used to initialize the Admin SDKs. See how to set up a Firebase project if you need documentation on generating your project credential and using it to authenticate the Admin SDKs.',
    'auth/reserved-claims': 'One or more custom user claims passed to setCustomUserClaims() are reserved. For example, OIDC specific claims (e.g. sub, iat, iss, exp, aud, or auth_time) should not be used as keys for custom claims.',
    'auth/session-cookie-expired': 'The provided Firebase session cookie has expired.',
    'auth/session-cookie-revoked': 'Firebase session cookies have been revoked.',
    'auth/uid-already-exists': 'Another user is already using the provided uid. Each user must have a unique uid.',
    'auth/unauthorized-continue-uri': 'The continuation URL domain is not whitelisted. Add it to the list in Firebase console.',
    'auth/user-not-found': 'There is no user record corresponding to the provided identifier.',
    'auth/wrong-password': 'Incorrect password.',
    'auth/unexpected': 'An unexpected error has occurred.'

}

export const es = {

    // HOME NAVIGATION
    home: "Inicio",
    habits: "Hábitos",
    streaks: "Rachas",

    madeBy: "Creado por",

    // AUTH
    login: "Iniciar sesión",
    register: "Crear cuenta",
    recoverAccount: "Recuperar cuenta",
    password: "Contraseña",
    repeatPassword: "Repetir contraseña",
    passwordForgotten: "¿Olvidaste tu contraseña? Recupera tu cuenta",
    createAccount: "¿No tienes una cuenta? Crea una aquí",
    loginInstead: "¿Ya tienes una cuenta? Inicia sesión aquí",
    invalidEmail: "Correo electrónico inválido",
    passwordRequired: "La contraseña es obligatoria",
    passwordCfmRequired: "La confirmación de contraseña es obligatoria",
    passwordsMatch: "Las contraseñas no coinciden",
    passwordMin: "La contraseña debe tener al menos 6 caracteres",
    emailRequired: "El correo electrónico es obligatorio",
    uploadPicture: "Subir imagen",
    cameraOrMedia: "¿Abrir la cámara o seleccionar desde la biblioteca de medios?",
    openCamera: "Abrir cámara",
    openMedia: "Abrir biblioteca de medios",
    yourName: "Tu nombre",
    nameRequired: "El nombre es obligatorio",
    
    // HOME
    hello: "Hola, ",
    emailValidationAlert: "No has validado tu correo electrónico. Por favor, revisa tu bandeja de entrada o:",
    emailValidationButton: "Reenviar correo de validación",
    noHabits: "¡No tienes hábitos para hoy!",
    createOrEdit: "Crear o editar uno",
    todaysHabits: "Hábitos de hoy - ",
    left: " faltantes",
    completedAll: "¡Has completado todos tus hábitos diarios! ¡Felicidades!",
    completedHabits: "Hábitos completados: ",
    youHavent: "No has completado ningún hábito hoy :(",
    
    // STREAKS
    more: "Ver más",
    theresNoHabits: "¡No hay hábitos! Crea uno",
    noStreaks: "Todavía no tienes rachas, ¡empieza a completar hábitos!",
    yourStreaks: "Tus rachas",
    youCompleted: "Has completado: ",
    day: "día",
    days: "días",
    inARow: " seguido",
    inARowPlural: " seguidos",
    totals: "Totales",
    
    // CALENDAR
    calendar: "Calendario",
    zeroCompleted: "0 hábitos completados",
    lessHalfCompleted: "Menos del 50% de los hábitos diarios",
    atLeast50: "Al menos el 50% de los hábitos diarios completados", 
    atLeast80: "Al menos el 80% de los hábitos diarios completados", 
    selectADay: "Selecciona un día con historial de hábitos",
    completed: "Completados:",
    incompleted: "Incompletos:",
    
    // HABITS
    habitsSetup: "Configuración de hábitos",
    addNewHabit: "Agregar nuevo hábito",
    yourHabits: "Tus hábitos",
    uSure: "¿Estás seguro?",
    habitWillDeleted: "El hábito se eliminará permanentemente",
    cancel: "Cancelar",
    delete: "Eliminar",
    monday: "Lunes", 
    tuesday: "Martes",
    wednesday: "Miércoles",
    thursday: "Jueves",
    friday: "Viernes",
    saturday: "Sábado",
    sunday: "Domingo",

    // AGREGAR O EDITAR HÁBITO
    habitNameRequired: "Se requiere el nombre del hábito",
    editHabit: "Editar Hábito",
    addHabit: "Agregar Hábito",
    chooseIcon: "Seleccionar ícono",
    habitName: "Nombre del Hábito",
    description: "Descripción",
    whatDays: "¿Qué días deseas hacerlo?",
    saveHabit: "Guardar Hábito",
    createHabit: "Crear Hábito",

    // CUENTA
    logout: "Cerrar Sesión",
    doYouLogout: "¿Deseas cerrar sesión?",
    account: "Cuenta",
    uploadPictureAlert: "* Cargar una foto de perfil",
    editProfile: "Editar Perfil",
    changePassword: "Cambiar Contraseña",

    // CAMBIAR CONTRASEÑA
    currentPassword: "Tu contraseña actual",
    newPassword: "Nueva contraseña",
    currentPasswordRequired: "Se requiere tu contraseña actual",
    newPasswordRequired: "Se requiere la nueva contraseña",

    // EDITAR PERFIL
    profileWillUpdated: "Tu perfil será actualizado",
    confirm: "Confirmar",
    forYourSecurity: "Para tu seguridad, escribe tu contraseña",
    saveChanges: "Guardar cambios",

    // CHANGE PASSWORD
    passwordWillChange: "Tu contraseña cambiará",

    // ALERTAS - CARGANDO: AUTENTICACIÓN
    creatingAccount: "Creando cuenta...",
    verificationSent: "Correo electrónico de verificación enviado, revisa tu bandeja de entrada",
    loggingIn: "Iniciando sesión...",
    loggingOut: "Cerrando sesión...",
    sendingRecover: "Enviando correo electrónico de recuperación...",
    emailSent: "Correo electrónico enviado, revisa tu bandeja de entrada",
    sendingValidation: "Enviando correo electrónico de validación...",
    updatingAccount: "Actualizando información de cuenta...",
    updatingEmail: "Actualizando correo electrónico...",
    updatingPassword: "Actualizando contraseña...",

    // ALERTAS - CARGANDO: HÁBITOS
    creatingHabit: "Creando hábito...",
    deletingHabit: "Eliminando hábito...",
    editingHabit: "Editando hábito...",
    completingHabit: "Completando hábito...",

    // ERRORS

    'auth/claims-too-large': 'La carga útil de la reclamación entregada supera el tamaño máximo de 1,000 bytes.',
    'auth/email-already-exists': 'Otro usuario ya está utilizando el correo electrónico proporcionado. Cada usuario debe tener un correo electrónico único.',
    'auth/id-token-expired': 'El token de ID de Firebase que se proporcionó está vencido.',
    'auth/id-token-revoked': 'Se revocó el token de ID de Firebase.',
    'auth/insufficient-permission': 'La credencial que se usó para inicializar el SDK de Admin no tiene permisos suficientes para acceder al recurso de Authentication solicitado. Consulta cómo configurar un proyecto de Firebase si necesitas ver la documentación para generar una credencial con los permisos apropiados y usarla a fin de autenticar los SDK de Admin.',
    'auth/internal-error': 'El servidor de Authentication encontró un error inesperado cuando se intentaba procesar la solicitud. Para obtener información adicional, revisa la respuesta del servidor de autenticación, que debería estar incluida en el mensaje de error. Si el error persiste, avísanos mediante nuestro canal de asistencia de informe de errores.',
    'auth/invalid-argument': 'Se proporcionó un argumento no válido para un método de autenticación. El mensaje de error debe incluir información adicional.',
    'auth/invalid-claims': 'Los atributos personalizados del reclamo entregados no son válidos.',
    'auth/invalid-continue-uri': 'La URL de continuación debe ser una string de URL válida.',
    'auth/invalid-creation-time': 'La hora de creación debe ser una string de fecha en formato UTC válida.',
    'auth/invalid-credential': 'La credencial que se usa para autenticar los SDK de Admin no se puede emplear a fin de realizar la acción deseada.',
    'auth/invalid-disabled-field': 'El valor que se proporcionó para la propiedad del usuario disabled no es válido. Debe ser un booleano.',
    'auth/invalid-display-name': 'El valor que se proporcionó para la propiedad del usuario displayName no es válido. Debe ser una string que no esté vacía.',
    'auth/invalid-dynamic-link-domain': 'El dominio del vínculo dinámico proporcionado no se configuró o no se autorizó para el proyecto actual.',
    'auth/invalid-email': 'El valor que se proporcionó para la propiedad del usuario email no es válido. Debe ser una dirección de correo electrónico de string.',
    'auth/invalid-email-verified': 'El valor que se proporcionó para la propiedad del usuario emailVerified no es válido. Debe ser un booleano.',
    'auth/invalid-hash-algorithm': 'El algoritmo de hash debe coincidir con las strings de la lista de algoritmos compatibles.',
    'auth/invalid-hash-block-size': 'El tamaño del conjunto de hash debe ser un número válido.',
    'auth/invalid-hash-derived-key-length': 'La longitud de la clave derivada de hash debe ser un número válido.',
    'auth/invalid-hash-key': 'La clave de hash debe ser un búfer de bytes válido.',
    'auth/invalid-hash-memory-cost': 'El costo de la memoria de hash debe ser un número válido.',
    'auth/invalid-hash-parallelization': 'La paralelización de hash debe ser un número válido.',
    'auth/invalid-hash-rounds': 'Las rondas de hash deben ser un número válido.',
    'auth/invalid-hash-salt-separator': 'El campo del separador de sal del algoritmo de hash debe ser un búfer de bytes válido.',
    'auth/invalid-id-token': 'El token de ID que se proporcionó no es un token de ID de Firebase válido.',
    'auth/invalid-last-sign-in-time': 'La hora del último acceso debe ser una string de fecha en formato UTC válida.',
    'auth/invalid-page-token': 'El token de página siguiente que se entregó en listUsers() no es válido. Debe ser una string válida que no esté vacía.',
    'auth/invalid-password': 'El valor que se proporcionó para la propiedad del usuario password no es válido. Debe ser una string con al menos seis caracteres.',
    'auth/invalid-password-hash': 'El hash de contraseñas debe ser un búfer de bytes válidos.',
    'auth/invalid-password-salt': 'La contraseña con sal debe ser un búfer de bytes válido.',
    'auth/invalid-phone-number': 'El valor que se proporcionó para phoneNumber no es válido. Debe ser una string de identificador que no esté vacía y que cumpla con el estándar E.164.',
    'auth/invalid-photo-url': 'El valor que se proporcionó para la propiedad del usuario photoURL no es válido. Debe ser una URL de string.',
    'auth/invalid-provider-data': 'providerData debe ser una serie de objetos UserInfo.',
    'auth/invalid-provider-id': 'providerId debe ser una string del identificador del proveedor compatible válida.',
    'auth/invalid-oauth-responsetype': 'Se debe configurar solo un responseType de OAuth como verdadera.',
    'auth/invalid-session-cookie-duration': 'La duración de la cookie de sesión debe ser un número válido en milisegundos que vaya entre los 5 minutos y las 2 semanas.',
    'auth/invalid-uid': 'El uid proporcionado debe ser una string no vacía con un máximo de 128 caracteres.',
    'auth/invalid-user-import': 'El registro de usuarios para importar no es válido.',
    'auth/maximum-user-count-exceeded': 'Se excedió la cantidad máxima de usuarios permitidos para importar.',
    'auth/missing-android-pkg-name': 'Si es obligatorio instalar la app para Android, debe proporcionarse un nombre de paquete de Android.',
    'auth/missing-continue-uri': 'Se debe proporcionar una URL de continuación válida en la solicitud.',
    'auth/missing-hash-algorithm': 'Para importar usuarios con hash de contraseñas, es necesario proporcionar el algoritmo de hash y sus parámetros.',
    'auth/missing-ios-bundle-id': 'Falta un ID del paquete en la solicitud.',
    'auth/missing-uid': 'Se requiere un identificador uid para la operación actual.',
    'auth/missing-oauth-client-secret': 'El secreto de cliente de la configuración de OAuth es obligatorio para habilitar el flujo de código de OIDC.',
    'auth/operation-not-allowed': 'El proveedor de acceso proporcionado está inhabilitado para tu proyecto de Firebase. Habilítalo en la sección Método de acceso de Firebase console.',
    'auth/phone-number-already-exists': 'Otro usuario ya utiliza el phoneNumber proporcionado. Cada usuario debe tener un phoneNumber único.',
    'auth/project-not-found': 'No se encontró ningún proyecto de Firebase para la credencial que se usó para inicializar los SDK de Admin. Consulta cómo configurar un proyecto de Firebase si necesitas ver la documentación para generar la credencial de tu proyecto y usarla a fin de autenticar los SDK de Admin.',
    'auth/reserved-claims': 'Una o más reclamaciones personalizadas de usuarios que se entregaron a setCustomUserClaims() están reservadas. Por ejemplo, no deben usarse reclamos específicos de OIDC (p. ej., sub, iat, iss, exp, aud o auth_time) como claves para reclamos personalizados.',
    'auth/session-cookie-expired': 'La cookie proporcionada de la sesión de Firebase venció.',
    'auth/session-cookie-revoked': 'Se revocaron las cookies de la sesión de Firebase.',
    'auth/uid-already-exists': 'Otro usuario ya utiliza el uid proporcionado. Cada usuario debe tener un uid único.',
    'auth/unauthorized-continue-uri': 'El dominio de la URL de continuación no está en la lista blanca. Inclúyelo en la lista en Firebase console.',
    'auth/user-not-found': 'No existe ningún registro de usuario que corresponda al identificador proporcionado.',
    'auth/wrong-password': 'Contraseña incorrecta',
    'auth/unexpected': 'Ha ocurrido un error inesperado'
}